FROM arm32v6/python:3-alpine3.6
RUN mkdir -p /app/etc && mkdir /app/blackhouse
WORKDIR /app
ENV PYTHONUSERBASE /app/vendor
ADD requirements.txt /app/
RUN pip3 install -r requirements.txt --user --upgrade
COPY blackhouse /app/blackhouse/
COPY docker-entrypoint.py /app
COPY docker-entrypoint-pizero-switch-server.py /app
COPY examples/configs/*.example /app/etc/
CMD /usr/local/bin/python3 docker-entrypoint-pizero-switch-server.py

EXPOSE 5000 5001
