version: '3.1'
services:
  control:
    image: drober/blackhouse:v1_piZeroW
    ports:
      - 5002:5002
      - 5003:5003
    volumes:
      - /app/etc:/app/etc
    networks:
      - blackhousenet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.role == worker ]
    labels:
      es.blackhouse.description: "Blackhouse Domotica"
      es.blackhouse.awesome: ""
networks:
  blackhousenet:
    driver: overlay
